### ISSUE TITLE
Incorporate @ericpashman's and @karl-chan's work

### ISSUE THREAD

**Issue by dimitri-xyz** [dimitri-xyz/coinbase-pro-exchange#1]
There are two forks from the old [repo](https://github.com/AndrewRademacher/coinbase-exchange/) that we should make the most of. Any suggestions on how to go about this are welcome here.

**Comment by ericpashman** [comment]
As I mentioned in the discussion at the old repo, I have a number of local commits that I haven't uploaded to GitHub, mainly because I was starting to make breaking changes to the basic API. But I’m happy to try to pull out the non-breaking changes and submit them here, as well as to go back and see what fixes and functionality I can incorporate here more delicately than I cared to on my own fork. I think I’ll have some time tomorrow to start on this.

@dimitri-xyz, thanks for the commit privileges. I’d prefer to submit pull requests for most changes so that you can look them over. Let’s start with that approach so we can discuss things and get on the same page. If you don’t have time for review as we move forward, I’ll commit directly as necessary.

**Comment by dimitri-xyz** [comment]
Sounds good to me! :-)

**Comment by ericpashman** [comment]
PR #10 just about finishes off all the contributions I can pull in from my old repo. Is there anything in particular we want from @karl-chan's fork? I haven't yet had a chance to look at it.

**Comment by ericpashman** [comment]
I took a quick look around @karl-chan's fork. It looks like he implemented about as much of the WebSocket API as I did at about the same time. Oh, well.

1. https://github.com/karl-chan/gdax-haskell/commit/b43f60eb374a3919c844ffda02cbe761ebd18210 This expansive commit, together with some older commits, has some additions and changes to the REST API that we probably want. I like the renaming of the `sbox` target to `demo`. There are some changes to the WebSocket API that we can use, but most of them are superceded by my recent PR.

2. https://github.com/karl-chan/gdax-haskell/commit/eb42183cf5b19b3d75c31657edf1c81234d6b62e This commit related to stop orders probably has some changes we want.

I'm realizing at this point that, given the size of many of these commits (including a huge amount of formatting changes), it will probably be easier just to look through each of the files, pick out what we want, and add it manually in new commits.

But, yes, I think there is some stuff we want there.

**Comment by dimitri-xyz** [comment]
I am thinking we might just have to bite the pulled and comb through his contributions too. I also had some other commits that I will have to pull-in one by one.

**Comment by ericpashman** [comment]
I’ll pull in the remaining bits of his code relevant to the WebSocket API after we commit my recent PR. I’ve looked at some off the other stuff, too, and have in mind a few changes to grab.

**Comment by dimitri-xyz** [comment]
I also had a few commits that were made after your fork, that I will look at.

**Comment by ericpashman** [comment]
I think the only thing left here is possibly to incorporate @karl-chan's work on stop orders, see my comment above. I'm closing this and will open a new issue about stop orders.
